### ISSUE TITLE
Any chance to have WordMove v5?

### ISSUE THREAD

**Issue by AndreaBarghigiani** [welaika/docker-wordmove#15]
Hi @pioneerskies,
don't want to rush or sound rude but since [you're updating the image](https://github.com/welaika/docker-wordmove/issues/14#issuecomment-582098442) it will be possible to have the new release of WordMove?

Maybe it's my ignorance about Docker but will I be able to update the gem with `gem update wordmove` without mess with the future updates of the container?

**Comment by alessandro-fazzi** [comment]
Hey @AndreaBarghigiani ,

I just `docker pull welaika/wordmove` and I get

```
> docker run --rm welaika/wordmove wordmove --version
5.0.2
```

What am I missing?

**Comment by AndreaBarghigiani** [comment]
That's strange, if I run your command I actually get the `5.0.2` version but if I create a container with it the version is `4.0.1`. Is it maybe because in my `docker-compose.yml` file I use the `:php7` tag?

Here's the full file:
```
version: "2"
services:
  mariadb:
    image: mariadb
    ports:
      - "8081:3306"
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: ---------
  wordpress:
    image: wordpress:latest
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    restart: on-failure:5
    links:
      - mariadb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ---------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8082:80
    links:
      - mariadb:mysql
    environment:
      PMA_USER: root
      PMA_PASSWORD: ---------
      PMA_HOST: mysql
  wordmove:
    tty: true
    depends_on:
      - wordpress
    links:
      - mariadb:mysql
    image: welaika/wordmove:php7
    restart: on-failure:5
    volumes:
      - ./public:/html
      - ~/.ssh:/root/.ssh
```
